[tool.poetry]
name = "parser-job"
version = "0.1.0"
description = ""
authors = ["<ivan kova1> <<ivan.2002aus@gmail.com>>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
setuptools = "^75.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
